name: shopify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-444.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.1
  carousel_slider: ^4.2.1
  fancy_shimmer_image: ^2.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

